# auto-generated by: bella secrets generate python
# project: my-project/production/vault
# generated at: 2025-01-15 10:30:00 UTC
# DO NOT edit manually — re-run bella secrets generate python to update.
from __future__ import annotations
import json
import os
import uuid
from dataclasses import dataclass
from urllib.parse import urlparse, ParseResult


@dataclass
class AppConfigShape:
    setting1: str
    setting2: int


class AppSecrets:
    @staticmethod
    def _require(key: str) -> str:
        v = os.environ.get(key)
        if v is None:
            raise RuntimeError(f"Required environment variable '{key}' is not set.")
        return v

    # String — third-party API key
    @property
    def external_api_key(self) -> str:
        return self._require("EXTERNAL_API_KEY")

    # Int — HTTP server port
    @property
    def port(self) -> int:
        return int(self._require("PORT"))

    # Bool — enable features toggle
    @property
    def enable_features(self) -> bool:
        return self._require("ENABLE_FEATURES").lower() == "true"

    # Uri — PostgreSQL connection string
    @property
    def database_url(self) -> ParseResult:
        return urlparse(self._require("DATABASE_URL"))

    # JSON — application configuration
    @property
    def app_config(self) -> AppConfigShape:
        data = json.loads(self._require("APP_CONFIG"))
        return AppConfigShape(**data)

    # GUID — application instance ID
    @property
    def app_id(self) -> uuid.UUID:
        return uuid.UUID(self._require("APP_ID"))
